### PR TITLE
(DHNSW) Overhaul of Partitioning

### PR DESCRIPTION
**Pull request by steiltre**
Templates dhnsw on a partitioner object to allow for experimentation with partitioning techniques. The voronoi_partitioner is the previous partitioning method employed in dhnsw code. An additional metric_hyperplane_partitioner is also included that creates balanced partitions.

@bwpriest I am leaving this PR as a draft until I know it does not interfere with your work and allows determinism in the ways you want.

### CODE REVIEW

**Comment by bwpriest** [comment]
@steiltre I've gone through some of the code, and I've noticed that you moved the seed setup inside of the new partitioner classes, to be accessed via [saltatlas::dhnsw::partition_data()](https://github.com/steiltre/saltatlas/blob/c6fbe6417816d5e7c380b74ad28ac9ea3f42f690/include/saltatlas/dhnsw/dhnsw.hpp#L24). However, this API requires that the data be provided as a ygm::container::bag. I need to use a ygm::container::map (because I assume updates can come from anywhere so keys need to be searchable during streaming sketch construction).

Do you advise constructing this map and converting it in-place into a bag, or can we add map versions of the partitioning functions?

**Comment by bwpriest** [comment]
I cannot seem to compile anything with the new dhnsw class because of a `std::uint64_t` and `std::size_t` mismatch. It looks like [saltatlas::voronoi_partitioner::find_point_partitions()](https://github.com/steiltre/saltatlas/blob/c6fbe6417816d5e7c380b74ad28ac9ea3f42f690/include/saltatlas/partitioner/voronoi_partitioner.hpp#L60) creates a `std::vector<std::uint64_t>`, which [saltatlas::dhnsw_detail::dhnsw_impl::add_data_point_to_insertion_queue()](https://github.com/steiltre/saltatlas/blob/c6fbe6417816d5e7c380b74ad28ac9ea3f42f690/include/saltatlas/dhnsw/detail/dist_index.hpp#L66) attempts to convert into a `std::vector<std::size_t>`. The same thing happens in `saltatlas::dhnsw_detail::query_engine_impl` [here](https://github.com/steiltre/saltatlas/blob/c6fbe6417816d5e7c380b74ad28ac9ea3f42f690/include/saltatlas/dhnsw/detail/query_engine.hpp#L45) and [here](https://github.com/steiltre/saltatlas/blob/c6fbe6417816d5e7c380b74ad28ac9ea3f42f690/include/saltatlas/dhnsw/detail/query_engine.hpp#L297). 

I got the same compiliation errors using gcc-9 and gcc-12.

Should these classes be templated on the vector value type, so that both sides use `std::vector<T>` or something similar?

**Comment by bwpriest** [comment]
I can confirm that I get these same compilation errors when I try to compile the saltaltas examples.

**Comment by bwpriest** [comment]
Interestingly, I just tried to compile the saltatlas examples on quartz, and was successful. I used gcc-11 installed with spack. I am not sure why that worked when my local environment did not. It is possible that quartz and my machine interpret `std::size_t` differently.

**Comment by bwpriest** [comment]
I've created a [PR](https://github.com/steiltre/saltatlas/pull/1) that fixes the issue raised in my [second comment above](https://github.com/LLNL/saltatlas/pull/9#issuecomment-1241301320).

**Comment by steiltre** [comment]
> 

Thought I had responded to this earlier, but must not have actually submitted...

The choice to use a `ygm::container::bag` was completely arbitrary and by no means necessary. Adding a version to use a `ygm::container::map` for your use case is completely reasonable. A version with an arbitrary container for data and lambdas to extract data from the container may be useful as well, but is probably overkill (and is still not a well-thought-out idea in my head).

**Comment by bwpriest** [comment]
I addressed both of my concerns in my PR, and I am ready to merge it if you are. If you're happy with the changes that I made, then I'd say that I'm ready for everything to get merged into `develop`.

**Comment by steiltre** [comment]
Merging changes after commits from this [PR](https://github.com/steiltre/saltatlas/pull/1).

**Pull request merged**
